#!/bin/bash
# Script prüft, ob Passwort auf Kommandozeile übergeben

if [ -z $1 ]
  then
    echo -n "Bitte Passwort eingeben: "
    read -s PASSWORD
    echo ""
  else
    PASSWORD=$1
  fi

echo "Unser Passwort lautet: "$PASSWORD

exit 0
