#!/bin/bash

SUM=0; N=1

if [ -z $1 ]
  then
    echo -n "Bitte MAX eingeben: "; read MAX;
  else
    MAX=$1
  fi

while [ $N -le $MAX ]
  do 
    SUM=$(($SUM + $N))
    N=$(($N + 1))
  done
echo "Summe der Zahlen von 1 bis $MAX = $SUM"
exit 0
